version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_NAME: mysql
    ports:
      - "${LOCAL_DATABASE_PORT}:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      net:
        ipv4_address: 10.5.0.2
  
  api:
    image: estuda-concursos
    build:
      context: projeto-rest-api-security/
      dockerfile: Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      LOCAL_DATABASE_URL: db
      LOCAL_DATABASE_PORT: 3306
    ports:
      - "${LOCAL_API_PORT}:8080"
    networks:
      net:
        ipv4_address: 10.5.0.3
    restart: on-failure:5
    depends_on:
      - db

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16