version: "3.9"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: myuser
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuser
      MYSQL_DATABASE: projetoweb