version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      SERVICE_NAME: mysql
    ports:
      - "${LOCAL_DATABASE_PORT}:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      net:
        ipv4_address: 10.5.0.2
  
  backend:
    image: estuda-concursos
    build:
      context: projeto-rest-api-security/
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${APP_ENV}
      DATABASE_URL: jdbc:mysql://db:3306/projetoweb_${APP_ENV}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${LOCAL_BACKEND_PORT}:8080"
    networks:
      net:
        ipv4_address: 10.5.0.3
    depends_on:
      - db

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16